In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  21.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051   138.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997   137.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB 741.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312   125.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB  11.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511     3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   3.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   6.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732     6.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447    55.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185    27.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   7.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB   8.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   6.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053    70.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643   176.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652   176.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 332.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   6.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB  11.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    55.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   6.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   21KB   7.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 252.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4083     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4550     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   40KB  17.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2908    66.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3942    92.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5860   135.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 313.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3073    35.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2669     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7820     4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 1183    27.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6027     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4067     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2894     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4347     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6330   144.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 306.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6640   200.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8019   185.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7577     4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   9.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4727     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6538     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5309     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8699     4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 424.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 258.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   5.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4589     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3757     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6328   144.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3147    73.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2464    56.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   32KB  15.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5205     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4012     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   15KB   8.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4481     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8736     5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   19KB 444.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   11KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4484     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   15KB  11.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 6951     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 5200     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4002     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4480     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB 262.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB 254.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   15KB   6.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 3970    93.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 1830    41.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3756    86.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3008     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5327   123.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7778    92.7KB/s   00:00

In [3]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 0
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "test": ["WATER27"],
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        print(
                            f"Warning: {mole_name} not found in {data_path.stem} data file"
                        )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ", "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
)

display(df_summary)

cc-pVDZ
Warning: W4_11-alh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-sih4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-bh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-si2h6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-b2h6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-sih3f not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ph3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2-sing not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-h2s not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h5f not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3f not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-nh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-methanol not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-bhf2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-h2o not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2ch not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-propyne not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-acetaldehyde not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-allene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-sif4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-bf3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h3f not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirane not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2f2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-alf3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-bef2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2c not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-acetic not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-h2co not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-h2cn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hcoh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hcoh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ketene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-formic not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hcnh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-glyoxal not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hcof not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2cl not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-cf4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hccf not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hcn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hnc not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-cch not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hco not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-f2co not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hocn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hooh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-t-n2h2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hnco not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c-n2h2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-cf2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-co2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-fccf not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-dioxirane not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ssh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hocl not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-nccn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ocs not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-clcn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hoo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hcno not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-honc not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hno not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hof not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hono not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hono not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-cs2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-hnnn not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-so3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-ccl2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-so2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hooo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-p4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hooo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-no2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-cl2o not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-s4-c2v not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-oclo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-f2o not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-fo2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-foof not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-o3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: W4_11-alh3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-sih4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-bh3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-si2h6 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-b2h6 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-sih3f not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h6 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h5f not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3f not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-nh3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-methanol not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-bhf2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2ch not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-propyne not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-acetaldehyde not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-allene not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-sif4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-bf3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h3f not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirane not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2f2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-alf3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-acetic not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-h2cn not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-ketene not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-formic not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hcnh not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-glyoxal not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hcof not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-cf4 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirene not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-f2co not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hocn not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hooh not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hnco not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c-n2h2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-fccf not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-dioxirane not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hcno not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-honc not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hono not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hono not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-hnnn not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-so3 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hooo not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hooo not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: W4_11-foof not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_72 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-p2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-p4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-p6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-sih4p not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-c2f6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-ethanol not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-ch3cooh not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-gly not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-phenol not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-ass not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-si2h6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-cys not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-phosphapyrrol not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-A not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-T not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-G not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-C not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: PA26-p4p not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-p6 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-glyp not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-phenol not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-ass not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-cys not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-A not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-T not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-G not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: PA26-C not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o2+_1.0 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o2+_1.25 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o2+_1.5 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o2+_1.75 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-bef not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-beo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-cao not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-hf not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-lif not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-lio not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-mgo not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-mgs not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-nao not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-f2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-f2s-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-h2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-h2s-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nf3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nf3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nh3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nh3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-nme3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-pf3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-pf3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-ph3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-ph3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-pme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-pme3-ch2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-ch2 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: YBDE18-nf3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: YBDE18-nh3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file
Warning: YBDE18-nme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ data file

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub1                                             3.601181  18.629823
sub2                                             5.700007   6.612165
sub3                                             3.648439   6.764537
sub4                                             2.277669   1.651300
sub5                                             1.775151   1.321288

data_path            ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                    1.46882  12.308217
sub2       210 / 243                                    0.00000   0.000000
sub3       170 / 194                                    0.00000   0.000000
sub4       217 / 244                                    0.00000   0.000000
sub5       268 / 291                                    0.00000   0.000000

data_path            ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       127 / 468                                   3.051654  15.860611
sub2         0 / 243                                   0.000000   0.000000
sub3         0 / 194                                   0.000000   0.000000
sub4         0 / 244                                   0.000000   0.000000
sub5         0 / 291                                   0.000000   0.000000

data_path
Type       Processed
sub1       203 / 468
sub2         0 / 243
sub3         0 / 194
sub4         0 / 244
sub5         0 / 291

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
YBDE18                                           8.128445   8.145395
ALKBDE10                                        10.401011  18.125250
AL2X6                                            6.683938   5.659146
PA26                                             3.603806   2.200767
DIPCS10                                          3.959661  12.310855
SIE4x4                                           4.526972  21.908521
G21IP                                            1.840062   8.953336
W4_11                                            2.977996  29.506869
G21EA                                            2.009397   9.754524
HEAVYSB11                                        4.230302   5.391477
NBPRC                                            4.266559   2.232550
ALK8                                             5.330166   4.400063
RC21                                             5.258815   4.820927
G2RC                                             3.605386   5.917204
BH76RC                                           1.125349  80.220383
FH51                                             3.129089   3.703658
TAUT15                                           2.322749   2.164531
DC13                                             8.769018  13.090863
MB16_43                                         15.909280  15.461608
DARC                                             8.461810  10.754152
RSE43                                            2.741250   3.157601
BSR36                                            2.745238   8.401182
CDIE20                                           2.104062   1.599507
ISO34                                            2.869448   2.001744
ISOL24                                           0.000000   0.000000
C60ISO                                           0.000000   0.000000
PArel                                            1.904611   1.743933
BH76                                             4.142984   9.107948
BHPERI                                           2.410479   3.268993
BHDIV10                                          3.670803   6.277708
INV24                                            0.000000   0.000000
BHROT27                                          1.458525   0.853379
PX13                                             7.171943  11.042025
WCPT18                                           4.076216   7.967153
RG18                                             0.315151   0.230018
ADIM6                                            4.186318   3.059030
S22                                              3.143330   2.291253
S66                                              2.658246   1.894710
HEAVY28                                          0.000000   0.000000
WATER27                                          0.000000   0.000000
CARBHB12                                         0.973519   1.632408
PNICO23                                          0.714591   0.776429
HAL59                                            2.587716   1.649787
AHB21                                            3.116596   2.453821
CHB6                                             3.579273   1.805320
IL16                                             2.246179   1.021067
IDISP                                           13.337525  13.125478
ICONF                                            1.737822   0.413804
ACONF                                            1.801305   0.546621
Amino20x4                                        1.642470   0.656235
PCONF21                                          3.485001   3.214782
MCONF                                            1.437692   1.956021
SCONF                                            0.984123   0.512352
UPU23                                            0.000000   0.000000
BUT14DIOL                                        0.858951   0.645099

data_path            ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
YBDE18       18 / 18                                   0.000000   0.000000
ALKBDE10       9 / 9                                   0.000000   0.000000
AL2X6          6 / 6                                   0.000000   0.000000
PA26         26 / 26                                   0.974996   2.675912
DIPCS10      10 / 10                                   2.799253  12.310855
SIE4x4       16 / 16                                   1.186737  21.257675
G21IP        36 / 36                                   1.498101   9.131019
W4_11      140 / 140                                   1.428623  16.710186
G21EA        25 / 25                                   1.209867   9.754524
HEAVYSB11      7 / 7                                   0.000000   0.000000
NBPRC        12 / 12                                   0.000000   0.000000
ALK8           8 / 8                                   0.000000   0.000000
RC21         21 / 21                                   0.000000   0.000000
G2RC         25 / 25                                   0.000000   0.000000
BH76RC       30 / 30                                   0.000000   0.000000
FH51         51 / 51                                   0.000000   0.000000
TAUT15       15 / 15                                   0.000000   0.000000
DC13         13 / 13                                   0.000000   0.000000
MB16_43      43 / 43                                   0.000000   0.000000
DARC         14 / 14                                   0.000000   0.000000
RSE43        43 / 43                                   0.000000   0.000000
BSR36        36 / 36                                   0.000000   0.000000
CDIE20       20 / 20                                   0.000000   0.000000
ISO34        34 / 34                                   0.000000   0.000000
ISOL24        0 / 24                                   0.000000   0.000000
C60ISO         0 / 9                                   0.000000   0.000000
PArel        20 / 20                                   0.000000   0.000000
BH76         76 / 76                                   0.000000   0.000000
BHPERI       26 / 26                                   0.000000   0.000000
BHDIV10      10 / 10                                   0.000000   0.000000
INV24         0 / 24                                   0.000000   0.000000
BHROT27      27 / 27                                   0.000000   0.000000
PX13         13 / 13                                   0.000000   0.000000
WCPT18       18 / 18                                   0.000000   0.000000
RG18         18 / 18                                   0.000000   0.000000
ADIM6          6 / 6                                   0.000000   0.000000
S22          22 / 22                                   0.000000   0.000000
S66          66 / 66                                   0.000000   0.000000
HEAVY28        0 / 0                                   0.000000   0.000000
WATER27       0 / 27                                   0.000000   0.000000
CARBHB12     12 / 12                                   0.000000   0.000000
PNICO23      23 / 23                                   0.000000   0.000000
HAL59        29 / 29                                   0.000000   0.000000
AHB21        21 / 21                                   0.000000   0.000000
CHB6           4 / 4                                   0.000000   0.000000
IL16         16 / 16                                   0.000000   0.000000
IDISP          6 / 6                                   0.000000   0.000000
ICONF        17 / 17                                   0.000000   0.000000
ACONF        15 / 15                                   0.000000   0.000000
Amino20x4    80 / 80                                   0.000000   0.000000
PCONF21      18 / 18                                   0.000000   0.000000
MCONF        51 / 51                                   0.000000   0.000000
SCONF        17 / 17                                   0.000000   0.000000
UPU23         0 / 23                                   0.000000   0.000000
BUT14DIOL    64 / 64                                   0.000000   0.000000

data_path           ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ             \
Type      Processed                                      AI AE     DFT AE
YBDE18       0 / 18                                   5.733823   8.852474
ALKBDE10      0 / 9                                   5.706127  18.125250
AL2X6         0 / 6                                   4.566135   4.152005
PA26         8 / 26                                   3.581816   2.023351
DIPCS10     10 / 10                                   3.454806  12.310855
SIE4x4       8 / 16                                   3.251565  21.908521
G21IP       35 / 36                                   2.920009   8.953336
W4_11      41 / 140                                   2.664505  23.678376
G21EA       25 / 25                                   1.769869   9.754524
HEAVYSB11     0 / 7                                   0.000000   0.000000
NBPRC        0 / 12                                   0.000000   0.000000
ALK8          0 / 8                                   0.000000   0.000000
RC21         0 / 21                                   0.000000   0.000000
G2RC         0 / 25                                   0.000000   0.000000
BH76RC       0 / 30                                   0.000000   0.000000
FH51         0 / 51                                   0.000000   0.000000
TAUT15       0 / 15                                   0.000000   0.000000
DC13         0 / 13                                   0.000000   0.000000
MB16_43      0 / 43                                   0.000000   0.000000
DARC         0 / 14                                   0.000000   0.000000
RSE43        0 / 43                                   0.000000   0.000000
BSR36        0 / 36                                   0.000000   0.000000
CDIE20       0 / 20                                   0.000000   0.000000
ISO34        0 / 34                                   0.000000   0.000000
ISOL24       0 / 24                                   0.000000   0.000000
C60ISO        0 / 9                                   0.000000   0.000000
PArel        0 / 20                                   0.000000   0.000000
BH76         0 / 76                                   0.000000   0.000000
BHPERI       0 / 26                                   0.000000   0.000000
BHDIV10      0 / 10                                   0.000000   0.000000
INV24        0 / 24                                   0.000000   0.000000
BHROT27      0 / 27                                   0.000000   0.000000
PX13         0 / 13                                   0.000000   0.000000
WCPT18       0 / 18                                   0.000000   0.000000
RG18         0 / 18                                   0.000000   0.000000
ADIM6         0 / 6                                   0.000000   0.000000
S22          0 / 22                                   0.000000   0.000000
S66          0 / 66                                   0.000000   0.000000
HEAVY28       0 / 0                                   0.000000   0.000000
WATER27      0 / 27                                   0.000000   0.000000
CARBHB12     0 / 12                                   0.000000   0.000000
PNICO23      0 / 23                                   0.000000   0.000000
HAL59        0 / 29                                   0.000000   0.000000
AHB21        0 / 21                                   0.000000   0.000000
CHB6          0 / 4                                   0.000000   0.000000
IL16         0 / 16                                   0.000000   0.000000
IDISP         0 / 6                                   0.000000   0.000000
ICONF        0 / 17                                   0.000000   0.000000
ACONF        0 / 15                                   0.000000   0.000000
Amino20x4    0 / 80                                   0.000000   0.000000
PCONF21      0 / 18                                   0.000000   0.000000
MCONF        0 / 51                                   0.000000   0.000000
SCONF        0 / 17                                   0.000000   0.000000
UPU23        0 / 23                                   0.000000   0.000000
BUT14DIOL    0 / 64                                   0.000000   0.000000

data_path
Type      Processed
YBDE18       9 / 18
ALKBDE10      9 / 9
AL2X6         3 / 6
PA26        15 / 26
DIPCS10     10 / 10
SIE4x4      16 / 16
G21IP       36 / 36
W4_11      80 / 140
G21EA       25 / 25
HEAVYSB11     0 / 7
NBPRC        0 / 12
ALK8          0 / 8
RC21         0 / 21
G2RC         0 / 25
BH76RC       0 / 30
FH51         0 / 51
TAUT15       0 / 15
DC13         0 / 13
MB16_43      0 / 43
DARC         0 / 14
RSE43        0 / 43
BSR36        0 / 36
CDIE20       0 / 20
ISO34        0 / 34
ISOL24       0 / 24
C60ISO        0 / 9
PArel        0 / 20
BH76         0 / 76
BHPERI       0 / 26
BHDIV10      0 / 10
INV24        0 / 24
BHROT27      0 / 27
PX13         0 / 13
WCPT18       0 / 18
RG18         0 / 18
ADIM6         0 / 6
S22          0 / 22
S66          0 / 66
HEAVY28       0 / 0
WATER27      0 / 27
CARBHB12     0 / 12
PNICO23      0 / 23
HAL59        0 / 29
AHB21        0 / 21
CHB6          0 / 4
IL16         0 / 16
IDISP         0 / 6
ICONF        0 / 17
ACONF        0 / 15
Amino20x4    0 / 80
PCONF21      0 / 18
MCONF        0 / 51
SCONF        0 / 17
UPU23        0 / 23
BUT14DIOL    0 / 64

In [ ]:
Error_molecule = [
    "G21IP-IP_80_cc-pVDZ_0-1_1_0.0000_default",
    "G21EA-EA_23n_cc-pVDZ_0-1_1_0.0000_default",
    "BH76-RKT15_cc-pVDZ_0-1_1_0.0000_default",
]
print(len(Error_molecule))

# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

str_print = ''
for molecule in Error_molecule:
    str_print += molecule.split("_cc-pVDZ_")[0] + " "
print(str_print)

3
G21IP-IP_80 G21EA-EA_23n BH76-RKT15